name: Run Android Unit Tests and Linter
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Create local.properties
        run: echo "" > local.properties

      # Execute unit tests
      - name: Unit Test
        run: ./gradlew testDebugUnitTest

      # Report the results
      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless

  android-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Create local.properties
        run: echo "" > local.properties

      # Execute lint
      - name: Run Lint
        run: ./gradlew lint
        continue-on-error: true

      - name: Check and Report Link Results
        uses: hidakatsuya/action-report-android-lint@v1.2.0
        with:
          result-path: '.github/workflows/lint-result.xml'